<a href="https://colab.research.google.com/github/azadeutsche114/Bag-of-words/blob/main/Edureka_Class_11_association_rule.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Association Rule Mining

In [ ]:
!wget https://www.dropbox.com/s/iivd4novdhlk7lb/groceries.csv
import pandas as pd
import numpy as np

--2022-09-13 02:11:29--  https://www.dropbox.com/s/iivd4novdhlk7lb/groceries.csv
Resolving www.dropbox.com (www.dropbox.com)... 162.125.3.18, 2620:100:6018:18::a27d:312
Connecting to www.dropbox.com (www.dropbox.com)|162.125.3.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/raw/iivd4novdhlk7lb/groceries.csv [following]
--2022-09-13 02:11:29--  https://www.dropbox.com/s/raw/iivd4novdhlk7lb/groceries.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc9892978088932122052973cb96.dl.dropboxusercontent.com/cd/0/inline/Bs02CHT_nbTGzWjjsvoVDToX-U6V8ueuy6uzDQLTTO9pfHjuBrZETLU-kJCA0o02mc5EzyZajnbiD7pM5MjXzvRwvlCCp6uprR10x5N8z8sTn1OfamV9QNk5hAYpkO304skcQrpTgDTacSD6uvYVIaeJmFmd3IqxHKYrwV5k3E7nxQ/file# [following]
--2022-09-13 02:11:30--  https://uc9892978088932122052973cb96.dl.dropboxusercontent.com/cd/0/inline/Bs02CHT_nbTGzWjjsvoVDToX-U6V8ueuy6uzDQLTTO9pfHjuBrZETLU-kJCA0o02mc5EzyZajnbiD7pM5MjXzvRwvlCCp6uprR10x5N8z8sTn1OfamV9QNk5hAYpkO304skcQrpTgDTacSD6uvYVIaeJmFmd3IqxHKYrwV5k3E7nxQ/file
Resolving uc9892978088932122052973cb96.dl.dropboxusercontent.com (uc9892978088932122052973cb96.dl.dropboxusercontent.com)... 162.125.3.15, 2620:100:6018:15::a27d:30f
Connecting to uc9892978088932122052973cb96.dl.dropboxusercontent.com (uc9892978088932122052973cb96.dl.dropboxusercontent.com)|162.125.3.15|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 510697 (499K) [text/plain]
Saving to: ‘groceries.csv’

groceries.csv       100%[===================>] 498.73K  --.-KB/s    in 0.05s

2022-09-13 02:11:30 (9.70 MB/s) - ‘groceries.csv’ saved [510697/510697]

In [ ]:
fileobj = open("groceries.csv","rt")
content = fileobj.readlines()
fileobj.close()

In [ ]:
content[:3]

['citrus fruit,semi-finished bread,margarine,ready soups\n',
 'tropical fruit,yogurt,coffee\n',
 'whole milk\n']

In [ ]:
'citrus fruit,semi-finished bread,margarine,ready soups\n'.strip() # remove the extra spaces in the string

'citrus fruit,semi-finished bread,margarine,ready soups'

In [ ]:
txns = [x.strip() for x in content]
txns[:3]

['citrus fruit,semi-finished bread,margarine,ready soups',
 'tropical fruit,yogurt,coffee',
 'whole milk']

In [ ]:
'citrus fruit,semi-finished bread,margarine,ready soups'.split(",")

['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups']

In [ ]:
all_txns = [each_txn.split(",") for each_txn in txns]
all_txns[:3] # data in the form of list inside a list

[['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['whole milk']]

In [ ]:
# Convert the data into one hot representation
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [ ]:
one_hot_encoding = TransactionEncoder()
one_hot_encoding.fit(all_txns)
one_hot_txns = one_hot_encoding.transform(all_txns)

In [ ]:
one_hot_txns.shape

(9835, 169)

In [ ]:
one_hot_txns[:2]

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False,  True, False, False, False, False, False, False,
        False, False, False, False, False, False, False,  True, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False,  True, False]])

In [ ]:
one_hot_txns = one_hot_txns.astype("int")
one_hot_txns[:2]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]])

In [ ]:
one_hot_encoding.columns_

['Instant food products',
 'UHT-milk',
 'abrasive cleaner',
 'artif. sweetener',
 'baby cosmetics',
 'baby food',
 'bags',
 'baking powder',
 'bathroom cleaner',
 'beef',
 'berries',
 'beverages',
 'bottled beer',
 'bottled water',
 'brandy',
 'brown bread',
 'butter',
 'butter milk',
 'cake bar',
 'candles',
 'candy',
 'canned beer',
 'canned fish',
 'canned fruit',
 'canned vegetables',
 'cat food',
 'cereals',
 'chewing gum',
 'chicken',
 'chocolate',
 'chocolate marshmallow',
 'citrus fruit',
 'cleaner',
 'cling film/bags',
 'cocoa drinks',
 'coffee',
 'condensed milk',
 'cooking chocolate',
 'cookware',
 'cream',
 'cream cheese',
 'curd',
 'curd cheese',
 'decalcifier',
 'dental care',
 'dessert',
 'detergent',
 'dish cleaner',
 'dishes',
 'dog food',
 'domestic eggs',
 'female sanitary products',
 'finished products',
 'fish',
 'flour',
 'flower (seeds)',
 'flower soil/fertilizer',
 'frankfurter',
 'frozen chicken',
 'frozen dessert',
 'frozen fish',
 'frozen fruits',
 'frozen meals',
 'frozen potato products',
 'frozen vegetables',
 'fruit/vegetable juice',
 'grapes',
 'hair spray',
 'ham',
 'hamburger meat',
 'hard cheese',
 'herbs',
 'honey',
 'house keeping products',
 'hygiene articles',
 'ice cream',
 'instant coffee',
 'jam',
 'ketchup',
 'kitchen towels',
 'kitchen utensil',
 'light bulbs',
 'liqueur',
 'liquor',
 'liquor (appetizer)',
 'liver loaf',
 'long life bakery product',
 'make up remover',
 'male cosmetics',
 'margarine',
 'mayonnaise',
 'meat',
 'meat spreads',
 'misc. beverages',
 'mustard',
 'napkins',
 'newspapers',
 'nut snack',
 'nuts/prunes',
 'oil',
 'onions',
 'organic products',
 'organic sausage',
 'other vegetables',
 'packaged fruit/vegetables',
 'pasta',
 'pastry',
 'pet care',
 'photo/film',
 'pickled vegetables',
 'pip fruit',
 'popcorn',
 'pork',
 'potato products',
 'potted plants',
 'preservation products',
 'processed cheese',
 'prosecco',
 'pudding powder',
 'ready soups',
 'red/blush wine',
 'rice',
 'roll products',
 'rolls/buns',
 'root vegetables',
 'rubbing alcohol',
 'rum',
 'salad dressing',
 'salt',
 'salty snack',
 'sauces',
 'sausage',
 'seasonal products',
 'semi-finished bread',
 'shopping bags',
 'skin care',
 'sliced cheese',
 'snack products',
 'soap',
 'soda',
 'soft cheese',
 'softener',
 'sound storage medium',
 'soups',
 'sparkling wine',
 'specialty bar',
 'specialty cheese',
 'specialty chocolate',
 'specialty fat',
 'specialty vegetables',
 'spices',
 'spread cheese',
 'sugar',
 'sweet spreads',
 'syrup',
 'tea',
 'tidbits',
 'toilet cleaner',
 'tropical fruit',
 'turkey',
 'vinegar',
 'waffles',
 'whipped/sour cream',
 'whisky',
 'white bread',
 'white wine',
 'whole milk',
 'yogurt',
 'zwieback']

In [ ]:
one_hot_txns_df = pd.DataFrame(one_hot_txns, columns= one_hot_encoding.columns_)
one_hot_txns_df.head()

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [ ]:
# Frequent itemsets
frequent_itemsets = apriori(one_hot_txns_df, min_support=0.02, use_colnames=True)
frequent_itemsets

      support                                         itemsets
0    0.033452                                       (UHT-milk)
1    0.052466                                           (beef)
2    0.033249                                        (berries)
3    0.026029                                      (beverages)
4    0.080529                                   (bottled beer)
..        ...                                              ...
117  0.032232                 (whipped/sour cream, whole milk)
118  0.020742                     (whipped/sour cream, yogurt)
119  0.056024                             (yogurt, whole milk)
120  0.023183  (whole milk, other vegetables, root vegetables)
121  0.022267           (yogurt, whole milk, other vegetables)

[122 rows x 2 columns]

In [ ]:
# build association rules
rules = association_rules(frequent_itemsets, metric = 'confidence', min_threshold=0.4)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(beef),(whole milk),0.052466,0.255516,0.021251,0.405039,1.585180,0.007845,1.251315
1,(butter),(whole milk),0.055414,0.255516,0.027555,0.497248,1.946053,0.013395,1.480817
2,(curd),(whole milk),0.053279,0.255516,0.026131,0.490458,1.919481,0.012517,1.461085
3,(domestic eggs),(whole milk),0.063447,0.255516,0.029995,0.472756,1.850203,0.013783,1.412030
4,(frozen vegetables),(whole milk),0.048094,0.255516,0.020437,0.424947,1.663094,0.008149,1.294636
5,(margarine),(whole milk),0.058566,0.255516,0.024199,0.413194,1.617098,0.009235,1.268706
6,(root vegetables),(other vegetables),0.108998,0.193493,0.047382,0.434701,2.246605,0.026291,1.426693
7,(whipped/sour cream),(other vegetables),0.071683,0.193493,0.028876,0.402837,2.081924,0.015006,1.350565
8,(root vegetables),(whole milk),0.108998,0.255516,0.048907,0.448694,1.756031,0.021056,1.350401
9,(tropical fruit),(whole milk),0.104931,0.255516,0.042298,0.403101,1.577595,0.015486,1.247252
10,(whipped/sour cream),(whole milk),0.071683,0.255516,0.032232,0.449645,1.759754,0.013916,1.352735
11,(yogurt),(whole milk),0.139502,0.255516,0.056024,0.401603,1.571735,0.020379,1.244132
12,"(whole milk, root vegetables)",(other vegetables),0.048907,0.193493,0.023183,0.474012,2.449770,0.013719,1.533320
13,"(other vegetables, root vegetables)",(whole milk),0.047382,0.255516,0.023183,0.489270,1.914833,0.011076,1.457687
14,"(yogurt, other vegetables)",(whole milk),0.043416,0.255516,0.022267,0.512881,2.007235,0.011174,1.528340

In [ ]:
rules.sort_values("lift", ascending=False).head(15)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
12,"(whole milk, root vegetables)",(other vegetables),0.048907,0.193493,0.023183,0.474012,2.449770,0.013719,1.533320
6,(root vegetables),(other vegetables),0.108998,0.193493,0.047382,0.434701,2.246605,0.026291,1.426693
7,(whipped/sour cream),(other vegetables),0.071683,0.193493,0.028876,0.402837,2.081924,0.015006,1.350565
14,"(yogurt, other vegetables)",(whole milk),0.043416,0.255516,0.022267,0.512881,2.007235,0.011174,1.528340
1,(butter),(whole milk),0.055414,0.255516,0.027555,0.497248,1.946053,0.013395,1.480817
2,(curd),(whole milk),0.053279,0.255516,0.026131,0.490458,1.919481,0.012517,1.461085
13,"(other vegetables, root vegetables)",(whole milk),0.047382,0.255516,0.023183,0.489270,1.914833,0.011076,1.457687
3,(domestic eggs),(whole milk),0.063447,0.255516,0.029995,0.472756,1.850203,0.013783,1.412030
10,(whipped/sour cream),(whole milk),0.071683,0.255516,0.032232,0.449645,1.759754,0.013916,1.352735
8,(root vegetables),(whole milk),0.108998,0.255516,0.048907,0.448694,1.756031,0.021056,1.350401
4,(frozen vegetables),(whole milk),0.048094,0.255516,0.020437,0.424947,1.663094,0.008149,1.294636
5,(margarine),(whole milk),0.058566,0.255516,0.024199,0.413194,1.617098,0.009235,1.268706
0,(beef),(whole milk),0.052466,0.255516,0.021251,0.405039,1.585180,0.007845,1.251315
9,(tropical fruit),(whole milk),0.104931,0.255516,0.042298,0.403101,1.577595,0.015486,1.247252
11,(yogurt),(whole milk),0.139502,0.255516,0.056024,0.401603,1.571735,0.020379,1.244132

In [ ]:
# if lift > 1 --> item A purchased will increase the probability of purchasal of item B
# if lift = 1 --> item A and item B are independent
# if lift < 1 --> item A and item B are alternate products to each other